### PR TITLE
Rename event handler prop for `Button` component

### PR DESCRIPTION
**Pull request by Ryukemeister**

### CODE REVIEW

**Review by niwsa — COMMENTED** [review]
Good catch 👍

**Comment by niwsa** [comment]
Seeing some issues while testing the Connections component with the changes ...

**Comment by Ryukemeister** [comment]
> Seeing some issues while testing the Connections component with the changes ...

Made some tweaks so should hopefully fix the issues now!

**Comment by niwsa** [comment]
The generated code for "react" at https://github.com/boxyhq/ui/blob/f96f15fcc05b54a176586dff218326b8a908b263/src/sso/connections/EditConnection/saml/index.lite.tsx#L162 
is not invoking the handler

Screenshot 2023-08-22 at 12 23 23 AM

**Comment by niwsa** [comment]
The vue build failure shows some errors.

**Comment by Ryukemeister** [comment]
> The generated code for "react" at
> 
> https://github.com/boxyhq/ui/blob/f96f15fcc05b54a176586dff218326b8a908b263/src/sso/connections/EditConnection/saml/index.lite.tsx#L162
> 
> 
> is not invoking the handler
> Screenshot 2023-08-22 at 12 23 23 AM
> I guess the takeaway is we should stick to `(event) => handler(event)` for handlers on native elements like form, input, button etc. So `onSubmit={(event) => state.saveSSOConnection(event)}` fixes it.

That's strange because I actually tested that piece and it was working for me but yes better to use `(event) => handler(event)` there.

**Comment by niwsa** [comment]
> That's strange because I actually tested that piece and it was working for me but yes better to use (event) => handler(event) there.
It's doing a browser submission to the page instead of the API route.

**Review by niwsa — APPROVED** [review]

**Pull request merged**
